volumes:
    database_volume:
        name: database_volume

services:
    db:
        image: postgres:14.2-bullseye
        volumes:
            - database_volume:/var/lib/postgresql/data
        environment:
            - POSTGRES_DB=${POSTGRES_DB}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        ports:
            - 15432:5432
        env_file:
            - .env

    api:
        build:
            context: api
            dockerfile: Dockerfile.dev
        ports:
            - 8000:8000
        user: "1000:1000" # on macOS and Linux, replace this with your real user id and group id
        volumes:
            - ./api:/app
        env_file:
            - .env
        environment:
            CORS_HOST: http://localhost:5173
            WAIT_HOSTS: db:5432
            DATABASE_URL: ${DATABASE_URL}

    ghi:
        image: node:lts-bullseye
        command: /bin/bash run.sh
        working_dir: /app
        user: "1000:1000" # on macOS and Linux, replace this with your real user id and group id
        volumes:
            - ./ghi:/app
        environment:
            VITE_API_HOST: http://localhost:8000
            BASE_URL: http://localhost:5173
        ports:
            - "5173:5173"
        env_file:
            - .env

    tests:
        build:
            context: ./api
            dockerfile: Dockerfile.dev
        env_file:
            - .env
        environment:
            PYTHONPATH: /app
            DATABASE_URL: ${DATABASE_URL}
        depends_on:
            - db
        volumes:
            - ./api:/app # Ensure the path points to your tests directory
        working_dir: /app
        command: pytest tests/
