FROM python:3.10-bullseye
RUN python -m pip install --upgrade pip

ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.9.0/wait /wait
RUN chmod +x /wait

WORKDIR /app

COPY requirements.txt requirements.txt
RUN python -m pip install -r requirements.txt


# Install development dependencies
RUN pip install pytest
# Install pytest-asyncio
RUN pip install pytest-asyncio

# Copy the entire api folder
COPY . /app
# If you're using a relational database and want migrations
# to be run automatically, use Option A, otherwise use Option B

# Set PYTHONPATH environment variable
ENV PYTHONPATH=/app


# Option A
CMD /wait && python -m migrations up && uvicorn main:app --reload --host 0.0.0.0

# Option B
# CMD /wait && uvicorn main:app --reload --host 0.0.0.0
